package com.hitsoft.dab;


/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */


public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines.

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.

         */
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int a=0x7f020000;
        public static final int app=0x7f020001;
        public static final int app1=0x7f020002;
        public static final int b=0x7f020003;
        public static final int back=0x7f020004;
        public static final int back0=0x7f020005;
        public static final int back4=0x7f020006;
        public static final int back5=0x7f020007;
        public static final int back6=0x7f020008;
        public static final int back8=0x7f020009;
        public static final int bk=0x7f02000a;
        public static final int button=0x7f02000b;
        public static final int button_style=0x7f02000c;
        public static final int c=0x7f02000d;
        public static final int d=0x7f02000e;
        public static final int esc=0x7f02000f;
        public static final int four=0x7f020010;
        public static final int ic_launcher=0x7f020011;
        public static final int join=0x7f020012;
        public static final int left=0x7f020013;
        public static final int logo=0x7f020014;
        public static final int one=0x7f020015;
        public static final int pk=0x7f020016;
        public static final int po=0x7f020017;
        public static final int pp=0x7f020018;
        public static final int right=0x7f020019;
        public static final int select=0x7f02001a;
        public static final int style=0x7f02001b;
        public static final int successlogo=0x7f02001c;
        public static final int textview_style=0x7f02001d;
        public static final int textview_style2=0x7f02001e;
        public static final int textview_style3=0x7f02001f;
        public static final int three=0x7f020020;
        public static final int two=0x7f020021;
    }
    public static final class id {
        public static final int LinearLayout1=0x7f090007;
        public static final int action_settings=0x7f090037;
        public static final int actvWord=0x7f09001a;
        public static final int cidian=0x7f090020;
        public static final int cidian1=0x7f090003;
        public static final int cidian2=0x7f090028;
        public static final int cidian3=0x7f090016;
        public static final int cidian4=0x7f090008;
        public static final int cut=0x7f090015;
        public static final int edit=0x7f090000;
        public static final int findBut=0x7f090025;
        public static final int frame1=0x7f090027;
        public static final int genderGroup=0x7f09000d;
        public static final int gonggulianxi=0x7f090023;
        public static final int gonggulianxi1=0x7f090006;
        public static final int gonggulianxi2=0x7f09002b;
        public static final int gonggulianxi3=0x7f090019;
        public static final int gonggulianxi4=0x7f09000b;
        public static final int gongneng=0x7f090022;
        public static final int gongneng1=0x7f090005;
        public static final int gongneng2=0x7f09002a;
        public static final int gongneng3=0x7f090018;
        public static final int gongneng4=0x7f09000a;
        public static final int insertBut=0x7f09001c;
        public static final int listview=0x7f090026;
        public static final int login_password=0x7f09002d;
        public static final int login_username=0x7f09002c;
        public static final int msg=0x7f09000c;
        public static final int mybut=0x7f09001b;
        public static final int next=0x7f090012;
        public static final int qianwangdenglu=0x7f090036;
        public static final int register_passwd=0x7f090032;
        public static final int register_submit=0x7f090034;
        public static final int register_username=0x7f090031;
        public static final int reregister_passwd=0x7f090033;
        public static final int rg=0x7f09001d;
        public static final int rh=0x7f09001f;
        public static final int s1=0x7f09000e;
        public static final int s2=0x7f09000f;
        public static final int s3=0x7f090010;
        public static final int s4=0x7f090011;
        public static final int search=0x7f090001;
        public static final int shengciben=0x7f090021;
        public static final int shengciben1=0x7f090004;
        public static final int shengciben2=0x7f090029;
        public static final int shengciben3=0x7f090017;
        public static final int shengciben4=0x7f090009;
        public static final int submit=0x7f090013;
        public static final int text=0x7f090002;
        public static final int text1=0x7f090024;
        public static final int tvWordItem=0x7f090035;
        public static final int txt=0x7f090014;
        public static final int unregister_login_button=0x7f09002e;
        public static final int user_login_button=0x7f09002f;
        public static final int user_register_button=0x7f090030;
        public static final int yh=0x7f09001e;
    }
    public static final class layout {
        public static final int activity_fanyi=0x7f030000;
        public static final int activity_function=0x7f030001;
        public static final int activity_gglx=0x7f030002;
        public static final int activity_main=0x7f030003;
        public static final int activity_mryj=0x7f030004;
        public static final int activity_shengciben=0x7f030005;
        public static final int user_login=0x7f030006;
        public static final int user_register=0x7f030007;
        public static final int word_list=0x7f030008;
        public static final int ykactivity_main=0x7f030009;
    }
    public static final class menu {
        public static final int main=0x7f080000;
    }
    public static final class raw {
        public static final int dictionary2=0x7f040000;
    }
    public static final class string {
        public static final int a=0x7f060018;
        public static final int action_settings=0x7f060001;
        public static final int app_name=0x7f060000;
        public static final int b=0x7f060019;
        public static final int c=0x7f06001a;
        public static final int chaxun=0x7f060003;
        public static final int cidian=0x7f060005;
        public static final int d=0x7f06001b;
        public static final int denglu=0x7f060010;
        public static final int fanhui=0x7f060013;
        public static final int fanyi=0x7f06000b;
        public static final int fanyihoudejieguo=0x7f06001f;
        public static final int gonggulianxi=0x7f06000a;
        public static final int gongguxunlian=0x7f060016;
        public static final int hello_world=0x7f060002;
        public static final int jrscb=0x7f060004;
        public static final int mima=0x7f060011;
        public static final int niyaofanyishenmeya=0x7f06001e;
        public static final int qsrsc=0x7f060007;
        public static final int queding=0x7f06000f;
        public static final int querenmima=0x7f06000e;
        public static final int rihanhuyi=0x7f060015;
        public static final int shengciben=0x7f060006;
        public static final int shuaxin=0x7f060008;
        public static final int tijiao=0x7f060009;
        public static final int tishi=0x7f060017;
        public static final int xiayiti=0x7f06001c;
        public static final int yinghanhuyi=0x7f060014;
        public static final int yonghuming=0x7f06000d;
        public static final int youkedenglu=0x7f060012;
        public static final int zhengquelv=0x7f06001d;
        public static final int zhuce=0x7f06000c;
    }
    public static final class style {
        /**
         Base application theme, dependent on API level. This theme is replaced
         by AppBaseTheme from res/values-vXX/styles.xml on newer devices.









         Theme customizations available in newer API levels can go in
         res/values-vXX/styles.xml, while customizations related to
         backward-compatibility can go here.









         Base application theme for API 11+. This theme completely replaces
         AppBaseTheme from res/values/styles.xml on API 11+ devices.

         API 11 theme customizations can go here.

         Base application theme for API 14+. This theme completely replaces
         AppBaseTheme from BOTH res/values/styles.xml and
         res/values-v11/styles.xml on API 14+ devices.

         API 14 theme customizations can go here.
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme.
         All customizations that are NOT specific to a particular API-level can go here.
         */
        public static final int AppTheme=0x7f070001;
        public static final int auto=0x7f07000f;
        public static final int button1=0x7f070019;
        public static final int button2=0x7f07001a;
        public static final int button3=0x7f07001b;
        public static final int button4=0x7f07001c;
        public static final int button5=0x7f07001d;
        public static final int edittext1=0x7f070003;
        public static final int edittext2=0x7f070004;
        public static final int edittext3=0x7f070005;
        public static final int edittext4=0x7f070006;
        public static final int edittext5=0x7f070007;
        public static final int edittext6=0x7f070008;
        public static final int framelayout1=0x7f07001e;
        public static final int framelayout2=0x7f07001f;
        public static final int linearlayout1=0x7f070009;
        public static final int linearlayout2=0x7f07000a;
        public static final int linearlayout3=0x7f07000b;
        public static final int linearlayout4=0x7f07000c;
        public static final int linearlayout5=0x7f07000d;
        public static final int linearlayout6=0x7f07000e;
        public static final int listview1=0x7f070002;
        public static final int radiobutton1=0x7f070014;
        public static final int radiobutton2=0x7f070015;
        public static final int radiobutton3=0x7f070016;
        public static final int radiobutton4=0x7f070017;
        public static final int radiobutton5=0x7f070018;
        public static final int radiogroup1=0x7f070010;
        public static final int radiogroup2=0x7f070011;
        public static final int radiogroup3=0x7f070012;
        public static final int radiogroup4=0x7f070013;
        /**  px
         */
        public static final int textview1=0x7f070020;
        public static final int textview2=0x7f070021;
        public static final int textview3=0x7f070022;
        public static final int textview4=0x7f070023;
        public static final int textview5=0x7f070024;
        public static final int textview6=0x7f070025;
        public static final int textview7=0x7f070026;
    }
}
